### ISSUE TITLE
Create a input which takes text and replaces the heading "EXPENSE TRACKER"

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Expense-Tracker-Hacktoberfest-2022#10]
- EXPENSE TRACKER

- Input Modal -> MY EXPENSE TRACKER -> heading changes to : MY EXPENSE TRACKER

**Comment by Abhishek3223** [comment]
**_hey i would like to do this_**

**Comment by Karan2310** [comment]
> hey i would like to do this

Sure!

**Comment by ayusshh19** [comment]
pls assign me this issue

**Comment by Karan2310** [comment]
> **_hey i would like to do this_**

You still working on it?
