### ISSUE TITLE
Round off the balance upto two decimal

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Expense-Tracker-Hacktoberfest-2022#16]

**Comment by kunalsingh1301** [comment]
please @Karan2310 assign me!!

**Comment by Karan2310** [comment]
> please @Karan2310 assign me!!

Sure!

**Comment by Sparsh752** [comment]
Please assign me

**Comment by Karan2310** [comment]
> please @Karan2310 assign me!!

You still working on it?

**Comment by MansiBhayade** [comment]
can you assign this to me ?

**Comment by ayusshh19** [comment]
pls assign me this issue

**Comment by Rajrupa123** [comment]
I want to resolve this issue. Kindly assign it to me
