### ISSUE TITLE
Prettier config file missing

### ISSUE THREAD

**Issue by Rohit-Saini7** [Google-Developer-Students-Club-DMCE/Expense-Tracker-Hacktoberfest-2022#21]
### What is the issue?

Nowadays everyone uses [Prettier](https://prettier.io/), An automated code formatting tool.

The issue is everyone have different **global settings** of prettier according to their style. BUT this can **cause useless changes** to opensource projects as many people works on same code.

So having a `prettier config file` inside project directory can resolve this issue.

### How to solve this issue?

adding a file `.prettierrc` and `.prettierignore` will solve this issue

**Comment by ayusshh19** [comment]
pls assign me this isssue

**Comment by RohitSaini7** [comment]
@Karan2310 Did you even read the issue once and understand what it says before adding `invalid` label to this.
