### ISSUE TITLE
On Deleting all expenses, Local storage functionality fails to add new expenses

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Expense-Tracker-Hacktoberfest-2022#24]

**Comment by Karan2310** [comment]
Also, remove hard coded expenses

**Comment by anurag0singh** [comment]
@Karan2310 would you please describe the problem a little more? It will be very helpful

**Comment by Karan2310** [comment]
@anurag0singh add one transaction -> delete all transaction -> try adding a transaction -> after reload it does not stay on the local storage

**Comment by Athi223** [comment]
I'd like to contribute to this
