### ISSUE TITLE
Add Input Validation

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Expense-Tracker-Hacktoberfest-2022#4]

**Comment by manastelavane** [comment]
I would like to work on this too

**Comment by Karan2310** [comment]
> I would like to work on this too

Sure

**Comment by Sparsh752** [comment]
Can I work on this

**Comment by ayusshh19** [comment]
pls assign me this issue

**Comment by Karan2310** [comment]
> I would like to work on this too

You still working on it?

**Comment by manastelavane** [comment]
Yes, i will do it by today
