### ISSUE TITLE
Fix Balance going Negative

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Expense-Tracker-Hacktoberfest-2022#5]

**Comment by manastelavane** [comment]
I would like to work on this issue

**Comment by Karan2310** [comment]
> I would like to work on this issue

Sure

**Comment by manastelavane** [comment]
So, do u want a alert banner like "Your expense is more than main balance", when expense is more than main amount?

**Comment by Karan2310** [comment]
> So, do u want a alert banner like "Your expense is more than main balance", when expense is more than main amount?

Yes like "Not enough balance"

**Comment by manastelavane** [comment]
ok

**Comment by manastelavane** [comment]
I have submitted the pull request. Please check

**Comment by manastelavane** [comment]
I have submitted the pull request. Please check @Karan2310
