### ISSUE TITLE
Balance Not Calculated properly

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Expense-Tracker-Hacktoberfest-2022#6]

**Comment by manastelavane** [comment]
Did u mean, after clicking on expense button and income button, in both cases it adds amount to main balance?

**Comment by Karan2310** [comment]
Not even adds exactly, You can check it by cloning the repo

**Comment by manastelavane** [comment]
Ok, check my pull request.

**Comment by manastelavane** [comment]
Plz add hacktoberfest-accepted tag
